### ISSUE TITLE
[ISSUE] BOT.PY

### ISSUE THREAD

**Issue by coolerspeex** [Hephyrius/binance_futures_bot#1]
When i start bot.py
ModuleNotFoundError: No module named 'binance_f'
 
even installed all requirements

COMMAND:
python -m pip install binance_f

ain't help

OUTPUT:
ERROR: Could not find a version that satisfies the requirement binance_f
ERROR: No matching distribution found for binance_f

**Comment by claudiomagallanes** [comment]
hello, how did you solve this problem?

**Comment by REPROGRAF** [comment]
> привет, как ты решил эту проблему?

python -m pip install binance-futures-connector
