### ISSUE TITLE
#global values used by bot to keep track of state

### ISSUE THREAD

**Issue by shin31120** [Hephyrius/binance_futures_bot#12]
#global values used by bot to keep track of state
entry_price = 0
exit_price_trigger = 0
liquidation_price = 0
in_position = False
side = 0

Is it needn't modify?

**Comment by ciclanoio** [comment]
Hello @shin31120  have you figured out how to set the values for the bot?

How for example to say the USD value of the bet?

Thanks

**Comment by shin31120** [comment]
It's depend on how much deposit in.
If you deposit 100 usd, I recommand 1~5 usd, 100 leverage.
This code has many error massage but hard to solve the problem.
Because little comment and not use of developer.

**Comment by Hephyrius** [comment]
> #global values used by bot to keep track of state
> entry_price = 0
> exit_price_trigger = 0
> liquidation_price = 0
> in_position = False
> side = 0
> 
> Is it needn't modify?

the values in the code are updated by the bot when it enters and exits a position. You only need to edit the config. Do not edit the code values unless you know what you're doing/want to add new features
