### ISSUE TITLE
another parameter to close the position?

### ISSUE THREAD

**Issue by ljieyao** [Hephyrius/binance_futures_bot#13]
can it have another parameter to close the position, for example, this position will be closed automatically after earning certain percentage, could you please help? thanks

**Comment by id3990** [comment]
I'm working on a fork of this strategy with a bunch of added features. Including stop loss, take profit, customizable parameters to exit a trade and an option for scalping. I'll keep you updated.

**Comment by ljieyao** [comment]
thanks, i am looking forward, plz keep me posted!

**Comment by ljieyao** [comment]
any update for this?

**Comment by nitheeshkavi** [comment]
hey any updates??

**Comment by Hephyrius** [comment]
Hey sorry, I'm too busy these days to add anything to the bot, but happy to accept any pull requests that add this feature. Feel free to add and make a PR. will merge!

**Comment by mseroczynski** [comment]
> I'm working on a fork of this strategy with a bunch of added features. Including stop loss, take profit, customizable parameters to exit a trade and an option for scalping. I'll keep you updated.

Hey there, is there any chance you would share mentioned fork?
