### ISSUE TITLE
Love your bot. I just have one request.

### ISSUE THREAD

**Issue by WillinPlaya** [Hephyrius/binance_futures_bot#18]
I have been trying to use your bot but I want to use it with Trading View Alerts to trigger the Buy and Sell signals instead of the built in strategy. I have tried modifying to code to do so but i am not successful. Can you provide a bot that can use the Tradng View Alerts as triggers ? I found one somewhere else but it only works on the spot market and i want to use your code since it`s designed for the Binance Futures market. Please help me out.

**Comment by WillinPlaya** [comment]
Also Your code will automatically reverse the trade with 1 signal that is the other reason i want to use your code with trading view alerts.

**Comment by Hephyrius** [comment]
I would love to add features but I'm strapped for time, feel free to contribute and I'll review and merge any good pull requests!
