### ISSUE TITLE
json read error

### ISSUE THREAD

**Issue by eth-man** [Hephyrius/binance_futures_bot#40]
im keep getting this message using Ubuntu and python 3.8

```Bot Starting
Encountered Exception Expecting value: line 1 column 1 (char 0)
Encountered Exception Expecting value: line 1 column 1 (char 0)
Encountered Exception Expecting value: line 1 column 1 (char 0)
Encountered Exception Expecting value: line 1 column 1 (char 0)
Encountered Exception Expecting value: line 1 column 1 (char 0)
Encountered Exception Expecting value: line 1 column 1 (char 0)

**Comment by Sanaikimdojin** [comment]
settings.json

"api_url" : "https://fapi.binance.com/" = X

"api_url" : "https://fapi.binance.com" = O

try this

From the may 31st, there will be one more / after the url.

If I delete the / after the old url, it works fine.

**Comment by eth-man** [comment]
wonderful!
thank you!

**Comment by keustii** [comment]
its not working for myself. :/ still having the same error

Encountered Exception Expecting value: line 1 column 1 (char 0)

Pyton 3.9
Windows Server 2016 (V 1607)
