### ISSUE TITLE
Visualize JSON data with dashboard..

### ISSUE THREAD

**Issue by mxwo93** [Hephyrius/binance_futures_bot#8]
Hi I'm new to coding really and would love to have the JSON information that's sent (assuming via TV webhook) formatted into a webpage that uses the JSON data and builds a table to have a nice little dashboard.

Any ideas of where to start or how to incporporate?

Thanks!

**Comment by Hephyrius** [comment]
The trades are logged and output as a csv. you can always import them into something like excel and make charts. I'm a bit too lazy/busy to make a flask app :P
